Add fullscreen toggle
ntnu-informatikk-2021/SDG-ontology-visualizer pull request #165
Opened 2021-04-11 18:59 UTC by AndreasWintherMoen

Closes #163 

I wasn't sure how to implement this but I think it turned out quite well. We'll probably have to test it on Mac and Windows as well to make sure there's no weird behaviour, but I've tested in Firefox and Chrome on Ubuntu and it works well here.

A lot of different components had to render differently when in fullscreen mode, so I used the Context API to share state across the whole app. I haven't used that much before, but I think it's implemented correctly and according to standards?

2021-04-11 19:42 UTC, erikskaar requested changes
I'm not too familiar with Context, but what exactly does it provide that we can't use Redux for? As far as i know, Redux can do everything Context does, but that might be wrong. Everything looks good though :)

2021-04-11 19:42 UTC, erikskaar commented on frontend/src/components/atoms/GraphSidebar.tsx
> +      // h={isFullscreen ? '80%' : '100%'}
```suggestion
```

2021-04-11 19:42 UTC, erikskaar commented on frontend/src/context/FullscreenContext.tsx
> +          console.log(`toggle fullscreen. New value: ${!isFullscreen}`);
```suggestion
```

2021-04-11 20:06 UTC, benedihm commented
Works fine on mac!

2021-04-11 20:10 UTC, yvindo reviewed
Looks great! Love the use of the isFullscreen boolean to toogle content returns.

2021-04-11 20:10 UTC, yvindo commented on frontend/src/components/atoms/Graph.tsx
> +        <AiOutlineFullscreen fontSize="32px" />
isFullscreen ? thisButton  :  buttonWithArrowsInwards;

2021-04-11 20:34 UTC, AndreasWintherMoen commented on frontend/src/components/molecules/GraphContainer.tsx
> +      w={isFullscreen ? '100vw' : ''}
width='' is the same as not setting width at all. Typescript and ESLint don't let me provide conditional props, so I had to solve it like that.

2021-04-11 20:39 UTC, AndreasWintherMoen commented
Fixed requested changes. Will have to change how fullscreen is rendered after #166 though, so I think we should merge that one first. We don't have to stress about the fullscreen feature before user testing on Monday.

2021-04-11 20:43 UTC, AndreasWintherMoen commented
> I'm not too familiar with Context, but what exactly does it provide that we can't use Redux for? As far as i know, Redux can do everything Context does, but that might be wrong. Everything looks good though :)

Yea I guess we could use Redux. Context just felt simpler because it was such a small thing, but I suppose it's unnecessary to have both Redux and Context in the same app. If we don't end up merging this before user tests I may do it with Redux instead.

2021-04-12 07:46 UTC, erikskaar approved these changes

2021-04-16 10:43 UTC, erikskaar approved these changes
🇹🇩

2021-04-16 10:53 UTC, merged